/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/burger.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material-color={'#792b1c'} material={materials.Material}          geometry={nodes.Burger.geometry} />
      <mesh material-color={'#ee851c'} material={materials.Material}          geometry={nodes.Bum_Bottom.geometry} />
      <mesh material-color={'#ffdd42'} material={nodes.Chees_Bottom.material} geometry={nodes.Chees_Bottom.geometry} />
      <mesh material-color={'#ffdd42'} material={nodes.Chees_Top.material}    geometry={nodes.Chees_Top.geometry} />
      <mesh material-color={'#ea0802'} material={nodes.Tomato_A.material}     geometry={nodes.Tomato_A.geometry} />
      <mesh material-color={'#ea0802'} material={nodes.Tomato_B.material}     geometry={nodes.Tomato_B.geometry} />
      <mesh material-color={'#ea0802'} material={nodes.Tomato_C.material}     geometry={nodes.Tomato_C.geometry} />
      <mesh material-color={'#a8e008'} material={nodes.Latice.material}       geometry={nodes.Latice.geometry} />
      <mesh material-color={'#ee851c'} material={materials.Material}          geometry={nodes.Bun_Top.geometry} />
      <mesh material-color={'#ffcd98'} material={nodes.Seeds.material}        geometry={nodes.Seeds.geometry} />
      {/* <mesh material-color={'#792B1C'} material={materials.Material1} geometry={nodes.Burger.geometry} />
      <mesh material-color={'#EE851C'} material={materials.Material2} geometry={nodes.Bum_Bottom.geometry} />
      <mesh material-color={'#FFDD42'} material={materials.Material3} geometry={nodes.Chees_Bottom.geometry} />
      <mesh material-color={'#FFDD42'} material={materials.Material4} geometry={nodes.Chees_Top.geometry} />
      <mesh material-color={'#EA0802'} material={materials.Material5} geometry={nodes.Tomato_A.geometry} />
      <mesh material-color={'#EA0802'} material={materials.Material6} geometry={nodes.Tomato_B.geometry} />
      <mesh material-color={'#EA0802'} material={materials.Material7} geometry={nodes.Tomato_C.geometry} />
      <mesh material-color={'#A8E008'} material={materials.Material8} geometry={nodes.Latice.geometry} />
      <mesh material-color={'#EE851C'} material={materials.Material9} geometry={nodes.Bun_Top.geometry} />
      <mesh material-color={'#FFCD98'} material={materials.Material0} geometry={nodes.Seeds.geometry} /> */}
    </group>
  )
}

useGLTF.preload('/burger.glb')
